### ISSUE TITLE
calls.log file isn't created if it doesn't already exist

### ISSUE THREAD

**Issue by theautumn** [theautumn/panel_gen#2]
A file named calls.log has to exist in the same directory as the .py  file. If it doesn't already exist, the program will throw an exception and die. To work around this issue, create a calls.log file as follows:

```
touch calls.log
chmod 777 calls.log
```

The file must be writable by whoever is running the program. It's easiest just to chmod 777 it, since it really contains no valuable data.

**Comment by paulseward** [comment]
Easiest doesn't mean safest!  :)

Allowing all users write access to a file which also has the executable bit set for all users (which you could then persuade another user or process to execute) isn't a great idea.

The best thing to do would be to get the .py file to create the file itself, as that will give it the right permissions.  If you *really* can't do that, `chmod 666` would be a little better as it wouldn't make the file executable.

I'd also suggest writing the log file to `/var/log/` so it's in a standard place on the system and can be automatically rotated by logrotate when it gets too big?

My python is a little too rusty to allow me to send you a PR though :(

**Comment by theautumn** [comment]
Fixed! Thanks for the suggestions.

-I've added exception handling so if the file doesn't exist, it will be created. 
-I've also moved the log file to /var/log/panel_gen/calls.log
-Finally, individual file permissions aren't an issue any longer, as long as /var/log/panel_gen is owned by 'asterisk', and that user has 'rw' permissions for that directory you should be good to go.
